version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://bank_admin:bank_password_qwertyuiop@bank-db:5432/bank_app?sslmode=disable
      - REDIS_ADDRESS=bank-redis:6379
    networks:
      - bank
    depends_on:
      - bank-db
      - bank-redis

  bank-db:
    image: postgres:16-alpine3.18
    container_name: pgdb-bank
    restart: always
    env_file:
      - .env.docker
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - bank_data:/var/lib/postgresql/data
    networks:
      - bank

  bank-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4-bank
    restart: always
    depends_on:
      - bank-db
    env_file:
      - .env.docker
    ports:
      - ${PGADMIN_LISTEN_PORT}:5051
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - bank

  bank-redis:
    image: redis:7-alpine
    container_name: bank-redis
    ports:
      - "6375:6379"


volumes:
  bank_data:

networks:
  bank:
